{% set name = "tiledb-vcf" %}
{% set version = "0.2.3" %}
{% set sha256 = "a947f506e8ae5063f22270ab5b205a07c78d41527b594c5278684ada1c57da88" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/TileDB-Inc/TileDB-VCF.git
  git_rev: master
  #fn: {{ name }}-{{ version }}.tar.gz
  #url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  #sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win or linux32 or py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - git
    - cmake
    - make
  run:
    - htslib >=1.8
    - tiledb 1.7.5
  host:
    - htslib >=1.8
    - tiledb 1.7.5

outputs:
  - name: libtiledbvcf
    script: install-libtiledbvcf.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - make
      host:
        - htslib >=1.8
        - tiledb 1.7.5
      run:
        - htslib >=1.8
        - tiledb 1.7.5

  - name: tiledbvcf-py
    script: build-tiledbvcf-py.sh
    requirements:
      host:
        #- {{ pin_subpackage('libtiledbvcf', exact=True) }}
        - libtiledbvcf
        - python
        - numpy >=1.16.*
        - pyarrow >=0.16
        - pybind11
      run:
        #- {{ pin_subpackage('libtiledbvcf', exact=True) }}
        #- {{ pin_compatible('numpy', lower_bound='1.16') }}
        - libtiledbvcf
        - python
        - numpy >=1.16.*
        - pyarrow >=0.16
        - pybind11
    imports:
      - tiledbvcf
    test:
      commands:
        - python -c "import tiledbvcf"

about:
  home: http://tiledb.com
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Efficient variant-call data storage and retrieval library using the TileDB storage library.'
  description: |
    TileDB-VCF is the python interface to the TileDB-VCF library.
  doc_url: https://docs.tiledb.com/developer/tiledbvcf/introduction
  dev_url: https://github.com/TileDB-Inc/TileDB-VCF

extra:
  recipe-maintainers:
    - ihnorton
    - shelnutt2
